# Generated by Django 3.1.5 on 2024-02-15 12:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('examination', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Authentication',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('authenticator_1', models.BooleanField(default=False)),
                ('authenticator_2', models.BooleanField(default=False)),
                ('authenticator_3', models.BooleanField(default=False)),
                ('course', models.CharField(default='', max_length=255)),
            ],
        ),
    ]
