# Generated by Django 3.1.5 on 2024-02-17 00:01

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('examination', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Authentication',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('authenticator_1', models.BooleanField(default=False)),
                ('authenticator_2', models.BooleanField(default=False)),
                ('authenticator_3', models.BooleanField(default=False)),
                ('course', models.CharField(default='', max_length=255)),
                ('timestamp', models.DateTimeField(default=django.utils.timezone.now)),
            ],
        ),
        migrations.DeleteModel(
            name='Authenticationexam',
        ),
    ]
