# Generated by Django 3.1.5 on 2024-02-17 10:21

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('examination', '0002_auto_20240217_0001'),
    ]

    operations = [
        migrations.CreateModel(
            name='hidden_grades',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('student_id', models.CharField(max_length=20)),
                ('course_id', models.CharField(max_length=50)),
                ('semester_id', models.CharField(max_length=10)),
                ('grade', models.CharField(max_length=5)),
            ],
        ),
    ]
